### ISSUE TITLE
Consider moving fmt.fbx to the "format" haxelib

### ISSUE THREAD

**Issue by kevinresol** [HeapsIO/heaps#466] opened 2018-11-06 11:35 UTC
So that other 3D libraries (e.g. kha) can use it as well.

**Comment by ncannasse** [comment] 2018-11-07 10:03
I'm not against it but the problem is that we can only move the Parser (Reader) and Data definition to format lib, while most of the code is actually in BaseLibrary which references a lot of Heaps data structures (Object, Skin, Joint, Matrix etc.)

Reading FBX format does not allow directly to make sense of it, as it's a document format from which specific information needs to be extracted.

**Comment by ncannasse** [comment] 2019-02-16 09:20
Closing for now.

**Closed by ncannasse** 2019-02-16 09:20 UTC
