### ISSUE TITLE
Alpha blending issue when using Sprite.drawTo

### ISSUE THREAD

**Issue by lbergman** [HeapsIO/heaps#419] opened 2018-09-04 13:37 UTC
Create a sprite with the following structure:
```
background:Sprite -> bakground:Bitmap
foreground:Sprite -> foreground:Bitmap
                  -> text:Sprite -> text:Text 
```
Add a blur based filter (Glow, Blur, DropShadow) to foreground -> text.

It will render as expected.
Now draw foreground to a texture, and replace it with the drawn texture.
background will now show through any semi transparent pixels.

See example code below. 

Here is the expected result when not using drawTo:
![drawtonot](https://user-images.githubusercontent.com/741170/45034611-44a3db80-b058-11e8-8f5b-6d3fb0d44bc3.PNG)

And here is using drawTo, where you can see the pattern in the background bleeding through:

![drawto](https://user-images.githubusercontent.com/741170/45034619-49688f80-b058-11e8-92f4-db352be9fa76.PNG)

```
import h2d.Tile;
import h2d.Bitmap;
import h2d.filter.DropShadow;
import h3d.mat.Data.TextureFlags;
import h3d.mat.Texture;

class Main extends hxd.App {
	static inline var RENDER_TO_BITMAP = true;

	override function init() {
		engine.backgroundColor = 0xFF000000;
		s2d.defaultSmooth = true;

		var holder = new h2d.Sprite(s2d);
		var background = new h2d.Sprite(holder);
		var foreground = new h2d.Sprite();

		var backTile = hxd.Res.orange.toTile();
		var frontTile = hxd.Res.cuadros.toTile();
		var w = frontTile.width;
		var h = frontTile.height;

		var back = new Bitmap(backTile, background);
		var front = new Bitmap(frontTile, foreground);

		var text = new h2d.Sprite(foreground);
		var tf = new h2d.Text(hxd.Res.Rubikdigits.build(80), text);
		tf.textColor = 0xFFFCED00;
		tf.text = '1234567890';
		tf.smooth = true;
		tf.textAlign = h2d.Text.Align.Center;
		tf.x = w / 2;
		text.filter = new Glow(0x00, 1., 300, 1., 1., true);

		if (RENDER_TO_BITMAP) {
			haxe.Timer.delay(() -> {
				foreground.y = 40;
				var texture = new Texture(w, h + 40, [TextureFlags.Target]);
				s2d.addChild(foreground);
				foreground.drawTo(texture);
				var bm = new Bitmap(Tile.fromTexture(texture), holder);
				bm.y = -40;
				foreground.remove();
			}, 0);
		} else {
			holder.addChild(foreground);
		}

		holder.x = (s2d.width - holder.getBounds().width) * 0.5;
		holder.y = (s2d.height - holder.getBounds().height) * 0.5;
	}

	static function main() {
		hxd.Res.initEmbed();
		new Main();
	}
}
```

**Comment by lbergman** [comment] 2018-09-04 14:56
Found a workaround. If I put the text in a bitmap instead of sprite, I can apply filter and blendmode to the same object, and then setting blendmode to AlphaAdd I get the expected result.

**Comment by ncannasse** [comment] 2018-10-17 21:30
Duplicate of #117

**Closed by ncannasse** 2018-10-17 21:30 UTC
