### ISSUE TITLE
Multiple problems with JS builds

### ISSUE THREAD

**Issue by b005t3r** [HeapsIO/heaps#238] opened 2017-02-20 20:25 UTC
1. Included examples don't run on Mac OS X and Chrome Version 56.0.2924.87 (64-bit). The DO work on Windows with the same Chrome version.
2. JS builds work really, really sluggish on Android (they work fine on iOS) and even crash on some phones.
3. I created these two sample projects, they're almost exactly the same, except one uses a texture and the other doesn't. The one with the texture DOES work without any problems, the one without a texture DOESN'T work on Chrome on Mac (works fine on Safari, doesn't work on Android, works fine on iOS).

Without texture: https://b005t3r.github.io/RotatingCube3D-hx/index.html (code: https://github.com/b005t3r/RotatingCube3D-hx/blob/master/src/Main.hx)

With texture: https://b005t3r.github.io/TexturedCube3D-hx/index.html (code: https://github.com/b005t3r/TexturedCube3D-hx/blob/master/src/Main.hx)

4. On Andorid and Mac it looks like AA is always ON (i checked the generated code, you don't pass the {antialiasing:false} when creating the context. On iOS it looks like AA is off.

It has to have something to do with the generated JS code, because I have no such problems with Unity WebGL builds and I tested pretty heavy GPU & memory stuff lately (like this: https://b005t3r.github.io/UltimateCRT/furries/ - it works everywhere with no problems).

5. I haven't tested this on Linux at all.

**Comment by ncannasse** [comment] 2017-02-20 20:28
Is 4. fixed now ?

**Comment by b005t3r** [comment] 2017-02-20 20:29
Need to check, will test this week and let you know.

**Comment by ncannasse** [comment] 2017-02-20 20:34
For the 2. , I'm using requestAnimationFrame for the main loop, and I don't perform any gl.finish/flush, I don't think that's related but that might be just a basic synchronization issue

**Comment by b005t3r** [comment] 2017-02-20 20:42
So maybe it's the same problem with 1.? Anyway, of you see a way to fix it, let me know and I'll test the fix.

**Comment by ncannasse** [comment] 2017-02-20 21:34
You can try adding a gl.finish() in GlDriver.present() to see if it helps

**Comment by b005t3r** [comment] 2017-02-21 10:26
OK, I tested with the new build. It works on Mac and it works on Android.

HOWEVER, on Android, it's noticeably slower if my device is in portrait orientation (maybe it has something to do with the backbuffer size?). In landscape orientation it works as fast as on my Mac (so at about 60 FPS, as measured by eye). 

I didn't add gl.finish() to the versions currently available at the links I gave earlier. I tested locally with gl.finish(), but it didn't make any difference.

**Comment by ncannasse** [comment] 2017-02-21 10:52
If you didn't add the gl.finish(), what do you mean by "the new build"?

**Comment by b005t3r** [comment] 2017-02-21 11:21
All right, from the start.

I updated heaps and built a fresh JS version with it. I tested this version on my Mac, iPad, Android phone and gave for other people to test with their devices. Compared to the previous version it works with no problems on all of them, except performance on Android is still not great (definitely it doesn't run at 60 FPS; on my device I can tell it runs noticeably faster then launched in horizontal orientation; it runs slower, below 30 fps by eye, if launched in portrait orientation).

Here you can see the difference between the old and the new build - there're more than just AA setting: https://github.com/b005t3r/TexturedCube3D-hx/commit/c7eff0a4e7afb2bcd54e5609e3cef8ea512c7f11

**Comment by b005t3r** [comment] 2017-02-21 11:28
After doing the above, I tested locally (on Mac, Android and iOS) with the added gl.finish(), but there was no difference, so I didn't pushed that to the repo.

**Comment by ncannasse** [comment] 2017-09-11 10:48
Seems like the problem is resolved, please reopen otherwise.

**Closed by ncannasse** 2017-09-11 10:48 UTC
