### ISSUE TITLE
Retina + Hashlink. Game is so small!

### ISSUE THREAD

**Issue by daimeng** [HeapsIO/heaps#767] opened 2020-02-18 02:49 UTC
Not an urgent issue, I'm using HTML output for now. I searched the words retina and osx, not much came up, so I'm creating a topic.

I'm guessing retina doesn't seem to play well with Hashlink version. Game runs very very tiny lol.
Is this known? Or am I just not missing some compile setting?

It looks fine when I run it on windows.

**Comment by Yanrishatum** [comment] 2020-02-18 08:03
Duplicate of #589

**Closed** 2020-02-18 16:39 UTC
