### ISSUE TITLE
Errors while building with OpenFL 4.8.1

### ISSUE THREAD

**Issue by b005t3r** [HeapsIO/heaps#234] opened 2017-02-18 18:48 UTC
```
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:547: characters 7-17 : Only inline or read-only (default, never) fields can be used as a pattern
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:579: characters 20-30 : Class<lime.graphics.opengl.GL> has no field RGBA32F
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:584: characters 17-30 : Class<lime.graphics.opengl.GL> has no field HALF_FLOAT (Suggestion: HIGH_FLOAT)
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:585: characters 20-30 : Class<lime.graphics.opengl.GL> has no field RGBA16F
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:587: characters 17-30 : Class<lime.graphics.opengl.GL> has no field HALF_FLOAT (Suggestion: HIGH_FLOAT)
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:588: characters 20-31 : Class<lime.graphics.opengl.GL> has no field ALPHA16F
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:591: characters 20-31 : Class<lime.graphics.opengl.GL> has no field ALPHA32F
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:603: characters 76-91 : Void should be Int
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:603: characters 76-91 : For function argument 'format'
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:610: characters 66-81 : Void should be Int
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:610: characters 66-81 : For function argument 'format'
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:800: characters 81-97 : Void should be Int
/usr/local/lib/haxelib/heaps/git/h3d/impl/GlDriver.hx:800: characters 81-97 : For function argument 'format'
/usr/local/lib/haxelib/heaps/git/hxd/impl/LimeStage.hx:297: characters 3-27 : Warning : This case is unused
/usr/local/lib/haxelib/heaps/git/hxd/impl/LimeStage.hx:298: characters 3-33 : Warning : This case is unused
/usr/local/lib/haxelib/heaps/git/hxd/impl/LimeStage.hx:299: characters 3-25 : Warning : This case is unused
/usr/local/lib/haxelib/heaps/git/hxd/impl/LimeStage.hx:301: characters 3-29 : Warning : This case is unused
/usr/local/lib/haxelib/heaps/git/hxd/impl/LimeStage.hx:302: characters 3-27 : Warning : This case is unused
/usr/local/lib/haxelib/heaps/git/hxd/impl/LimeStage.hx:303: characters 3-27 : Warning : This case is unused
/usr/local/lib/haxelib/heaps/git/hxd/impl/LimeStage.hx:304: characters 3-23 : Warning : This case is unused
/usr/local/lib/haxelib/heaps/git/hxd/impl/LimeStage.hx:320: characters 3-35 : Warning : This case is unused
/usr/local/lib/haxelib/heaps/git/hxd/System.hx:371: characters 7-22 : Too many arguments
```

**Comment by ncannasse** [comment] 2017-02-19 19:55
Duplicate of #227

**Closed by ncannasse** 2017-02-19 19:55 UTC
