### ISSUE TITLE
Failed to assign index while spliting skin Error Message

### ISSUE THREAD

**Issue by kiroukou** [HeapsIO/heaps#905] opened 2020-11-04 13:24 UTC
#17 could this be related?

We do have an animated model that triggers the following error : "Failed to assign index while spliting skin"

Shouldn't be a bones limit, any insights to share with us about the reason of that error?

Thanks

**Comment by ncannasse** [comment] 2020-11-04 14:03
This occurs on Skin.split so it's definitely an issue with too many bones.
This can be fixed by increasing maxBones. We didn't hit into this issue with any of our models in past years so there might be something wrong with the skin itself, such as it being shared by several objects, etc.

**Closed by ncannasse** 2020-11-04 14:03 UTC

**Comment by ncannasse** [comment] 2020-11-04 14:04
Another error might be if all bones are used by all vertexes, making impossible to split vertexes by bones groups.

**Comment by kiroukou** [comment] 2020-11-04 15:17
> Another error might be if all bones are used by all vertexes, making impossible to split vertexes by bones groups.
Shouldn't be that scenario. We can inspect vertexes, maximum of 3 bones are linked.

We do have in a lot of our models, more that the 34 bones limit, and the split scenario does work pretty well. That's the first case we encounter where the error occurs. (92 bones).

We did solved the issue so far, by increasing the maxBonesPerSkin value, but still interessted to have a better understanding of what is happening.
The comments before throw talks about heuristic not being able to handle free joints ?

**Comment by ncannasse** [comment] 2020-11-04 16:14
The problem is the following:

you have vertexes that uses up to 3 bones
a single draw call (set of triangles) can use up to 34 bones
you need to split your mesh into N set of triangles, each set vertexes using less than 34 unique bones.

also, each bone should be assigned an unique index (splitIndex) which it will use for each vertex list it's part of.
That's where the heuristic fails : some bone cannot find an index that will is "free" for all sets (permutations) it's part of. It would require trying to "solve" this problem using maybe some kind of loop to prioritize this particular bone.

Can you try using using this version that does some retry and giving the failing bone higher priority ?
https://gist.github.com/ncannasse/72a0969404026a27ca124961be50c5f4

**Comment by kiroukou** [comment] 2020-11-04 17:47
Ok thanks a lot for the explanations. 
> also, each bone should be assigned an unique index (splitIndex) which it will use for each vertex list it's part of. 
was the part missing for me.

The gist does solve the issue we have. Model now loads correctly without modifiying maxBonesPerSkin property on HmdOut

Thanks !
