### ISSUE TITLE
Using 'engine.setRenderZone' breaks 'h2d.Object' filters

### ISSUE THREAD

**Issue by RobertBorghese** [HeapsIO/heaps#517] opened 2019-01-02 19:59 UTC
Observe the following application:
```hx
class Main extends hxd.App {
	override function init() {
		var text = new h2d.Text(hxd.res.DefaultFont.get(), s2d);
		text.filter = new h2d.filter.Outline(1, 0xffff0000);
		text.x = 100;
		text.y = 100;
		text.text = "Hello World!";

		engine.setRenderZone(20, 20, 600, 400);
	}

	static function main() {
		new Main();
	}
}
```

In this example, the text does not appear as it should. However, if you remove the `engine.setRenderZone`, the text appears as desired. On the other hand, removing the assignment of `text.filter` also allows the text to appear with the render zone set up. There is a clear conflict with the two features.

This issue persists with any object type that uses a filter while the engine has a render zone set up.

**Comment by ncannasse** [comment] 2019-01-02 23:31
Duplicate of #201

**Closed by ncannasse** 2019-01-02 23:31 UTC
