### ISSUE TITLE
[RFC] Library-provided default converts

### ISSUE THREAD

**Issue by Yanrishatum** [HeapsIO/heaps#743] opened 2020-01-06 01:31 UTC
After introduction of FileConverter, only way to add custom converts is via props.json, while in old system it could be done via macro. This change essentially disabled ability of external libraries (read: Heeps) to add it's own default converts (e.g. gif convert) without extreme hackery of patching FileConverter class. 
Proposal:
Expose API to add that allows adding custom Converts via macro api (or at compilation time). While converts are registered, they cannot be enabled without mentioned manual involvement.

Possible solutions:
* Alter register method with extra parameter: `defaultConvert:Bool = false`, which would then affect if said convert is enabled by default. Then, instead of hard-coded list FileConvert grabs a list of converts that are enabled by default.
* Use same approach as `hxd.res.Config` and expose that list for macro to edit. This is more or less old approach, but provides less clarity on how it supposed to work.

Example use case:
I have a GifConvert class in Heeps that converts gif files into png atlases accompanying with giff metadata file that holds information about frame delays, image dimensions, etc. That is done to ease up loading of gif animations, as I use them extensively in my workflow when working with pixelart (asking artists to "just throw me that gif" is far more comfortable for them compared to doing sprite sheets, as pretty much always PA does not utilize semi-transparency) and using convert to preprocess them into format that more optimal for Heaps to render is logical. But right now it's not possible to enable said convert by default unless I use props.json and specify it directly.
(Also same convert makes me want to make ability to store more than one file into .tmp with one Convert, as right now I have to store png file in main res directory)

**Comment by ncannasse** [comment] 2020-01-06 19:20
Any converter that is compiled with the "program" (either the game or a hide plugin or a commandline PAK builder) can be used using props.json without requiring any change to FileConverter.

As "default converts configuration", I think you're referring to https://github.com/HeapsIO/heaps/blob/master/hxd/fs/FileConverter.hx#L43

One possibility would be to have this default configuration stored in a JSON that would be embedded at compile time, and allow a macro to bind another file instead of the std one. Would that work for you ?

**Comment by ncannasse** [comment] 2020-01-06 19:24
There was some discussion regarding storing metadata into .tmp , I think @D0pu even had a working implementation at some point but I don't think it was merged

**Comment by Yanrishatum** [comment] 2020-01-06 20:47
>> As "default converts configuration", I think you're referring to

Yes. Previously it was possible to add those from macro, without having to go trough props.json, which is paramount for external libraries that provide converts that have to be enabled by default. Easy to understand sample: Library that adds custom font format support. And to make it work with Heaps seamlessly - it needs to add Convert that is enabled by default for those font files when library is added to hxml which would convert it to regular Heaps bfnt file (because it's a part of adding said support). Currently it's not possible.

>> One possibility would be to have this default configuration stored in a JSON that would be embedded at compile time, and allow a macro to bind another file instead of the std one. Would that work for you ?

I don't think it would be a good solution, as that would introduce conflicts when multiple libraries want to add default converts. E.g. library A overrides default file, then library B overrides default file, and as a result converts added by library A no longer present. Plus there would be a need to also include fbx/fnt converts to that file as to not break Heaps default convert system.

>> storing metadata into .tmp
And again, point of my RFC is to enable ability of external libraries to add enabled by default Converts without extra actions from user. I'm not sure how metadata in tmp would help in that direction.

**Comment by ncannasse** [comment] 2020-01-06 20:56
What about then a macro than would "add" configuration files, that would be as many json that either overrides or adds rules to default config ?

The problem is that we also want to achieve the converter injection at macro level (for hxd.res.Embed for instance) and that was quite hard to do with previous implementation.

**Closed** 2020-09-27 08:59 UTC
