### ISSUE TITLE
Particles broken with dce full

### ISSUE THREAD

**Issue by lbergman** [HeapsIO/heaps#487] opened 2018-11-29 14:15 UTC
Seems like particles will not render when using dce full.
Adding @:keep to ParticleGroup getFields fixes the issue.
Will try --macro keep for now, but can make a PR when I have a little time.

**Comment by lbergman** [comment] 2018-11-29 14:35
No luck with macro keep, so created a PR:
https://github.com/HeapsIO/heaps/pull/488

**Comment by ncannasse** [comment] 2018-12-18 10:08
On which Haxe version do you have this behavior?

**Comment by lbergman** [comment] 2018-12-18 12:04
I'm using Haxe 4-preview.5

**Comment by ncannasse** [comment] 2019-02-16 09:25
With Haxe RC1 and -dce full, the particles2d sample from Heaps seems to work correctly.
Closing, request if you find a reproducible sample with RC1

**Closed by ncannasse** 2019-02-16 09:25 UTC

**Comment by RollinBarrel** [comment] 2019-08-24 02:36
On JS target, while ```-dce full``` does not break particles2d sample, it breaks h2d.Particles everywhere else for me:
```hxml
-lib heaps
-main Main
-dce full
-js game.js
```
```haxe
import h2d.Particles;
class Main extends hxd.App {
    static function main() {
        new Main();
    }
    override function init() {
        var p = new Particles(s2d);
        var g = new ParticleGroup(p);
        p.addGroup(g);
        g.emitDist = s2d.width;
    }
}
```
results in black screen.
4.0.0-RC3, latest git Heaps

**Comment by zommerfelds** [comment] 2022-08-29 08:18
After frustrating debugging for 1h I found out the culprit was DCE. Maybe the problem is not fixed? I'm running with:

Haxe: 4.2.5
Target: JS
Heaps: 1.9.1

https://github.com/HeapsIO/heaps/pull/488 fixes the issue for me. Can we consider merging it?

As a workaround, calling `Particles.save()` makes it work. I don't understand how the reflection for loading and saving is impacting the functionality.
